name: student1
device: cuda
num_epochs: 30
data_dir: /quyennt/sexy/data/pseudo_label/pseudo_label_1.csv
data_name: pseudo_label_1
batch_size: 32
model_name: efficientnet_b1
model_path: ckps/student0_efficientnet_b1_ckps_0.962.pt
model_resume: True
run_name: TRAIN_STUDENT1_SEXY
use_mlflow: True
optimizer: Adan
loss: LabelSmoothing
lr: 0.001
smoothing_value: 0.1